name: Artifacts download

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: 01 Starting Project
      - name: Lint
        run: npm run lint
        working-directory: 01 Starting Project

      - name: Run tests
        run: npm run test
        working-directory: 01 Starting Project

      - name: Build
        run: npm run build
        working-directory: 01 Starting Project
      - name: Verify build output
        run: ls -la dist
      - name: Download artifacts
        uses: actions/upload-artifact@v4
        with:
         name: artifacts
         path: dist
