name: deployment2-multijob

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        working-directory: demo-project2/01 Starting Project
  test:   
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
        working-directory: demo-project2/01 Starting Project
  deploy: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci      
      - name: Build
        run: npm run build
        working-directory: demo-project2/01 Starting Project
      - name: Deploy
        run: echo "deploying code.."
        
      
